Fatal Exeption
03-21 14:50:58.895 29848-29955/com.android.jimitjaishwal.moviesplex
E/AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #1
Process: com.android.jimitjaishwal.moviesplex, PID: 29848
java.lang.RuntimeException: An error occurred while executing
doInBackground()
at
android.support.v4.content.ModernAsyncTask$3.done(ModernAsyncTask.java:161)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: uri
at
com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
at android.content.ContentResolver.query(ContentResolver.java:515)
at
android.support.v4.content.ContentResolverCompatJellybean.query(ContentResolverCompatJellybean.java:33)
at
android.support.v4.content.ContentResolverCompat$ContentResolverCompatImplJB.query(ContentResolverCompat.java:57)
at
android.support.v4.content.ContentResolverCompat.query(ContentResolverCompat.java:125)
at
android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:59)
at
android.support.v4.content.CursorLoader.loadInBackground(CursorLoader.java:37)
at
android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:299)
at
android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:57)
at
android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:45)
at
android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:138)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
at java.lang.Thread.run(Thread.java:761) 

[ 03-21 14:50:58.903 29848:29848 D/         ]
HostConnection::get() New Host Connection established 0x72910c0b22e0,
tid 29848